const USERACTIONTYPE = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_USER_CREDENTIAL: 'SET_USER_CREDENTIAL',
    SET_RECEIVER_EMAIL: 'SET_RECEIVER_EMAIL',
    USER_LOGOUT: 'USER_LOGOUT'
};

export default USERACTIONTYPE;
